### ISSUE TITLE
God modes "AI Control" Confusion

### ISSUE THREAD

**Issue by Luselmases** [ABJ4403/Payback2_CHEATus#9]
### Checklist
- [X] I am using the latest version of the script
- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to control AI with the script but i only spect and i cant control,how i control ?

### Version

2.104.12.4

### Steps to reproduce

1. Run script
2. Select God mode > AI Control
3. *expects ability to control other bots/players/AIs*

**Comment by ABJ4403** [comment]
Sorry took long time to reply. What do you mean by "Ia control" ?

**Comment by Luselmases** [comment]
The Ai control,control bots like MrPink,etc

**Comment by Luselmases** [comment]
In God mode

**Comment by Luselmases** [comment]
Say that,Cant find the specific set of number,disable opt in config file,i disabled,and i cant control bots or use God Mode pls help.Thanks

**Comment by Luselmases** [comment]
> 

God modes,control bots

**Comment by ABJ4403** [comment]
> > 
> 
> God modes,control bots

God modes "AI Control" means that your player character controls will be overriden by the game AI logics, this usually used in Race/Sprint/Knockout matches

**Comment by Luselmases** [comment]
Ok

**Comment by Luselmases** [comment]
But is posible to control that Ai,i see videos that control the bots,im doing a proyect with that and i need that,you should be add that in the script

**Comment by Luselmases** [comment]
https://mega.nz/file/df0yna7Z#E_Jfa9ercPL5k4lWg0LmlOYeiMuUff9LwR2vgf40qK0

**Comment by ABJ4403** [comment]
> But is posible to control that AI, i see videos that control the bots, i'm doing a project with that and i need that, you should be add that in the script

Yes you can do it manually (which is quite hard), implementing this to a script is a whole different level and i dont even know how to find offset values for specific AIs, though i can do player override (but still need to know that offset to change control mode from AI to Player).

**Comment by Luselmases** [comment]
Oh,sorry,okay i try,thanks for result my question

**Comment by ABJ4403** [comment]
You're welcome! If you have any issues, don't be hesitant to make another bug report
